
-- Creación de la tabla bakugan
CREATE TABLE bakugan (
    id INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    attribute_primary VARCHAR(50) NOT NULL,
    attribute_secondary VARCHAR(50)
);

-- Inserción de 50 Bakugan
INSERT INTO bakugan (id, name, attribute_primary, attribute_secondary) VALUES
(1, 'Dragonoid', 'Pyrus', NULL),
(2, 'Tigrerra', 'Haos', NULL),
(3, 'Preyas', 'Aquos', NULL),
(4, 'Hydranoid', 'Darkus', NULL),
(5, 'Skyress', 'Ventus', NULL),
(6, 'Gorem', 'Subterra', NULL),
(7, 'Ingram', 'Ventus', NULL),
(8, 'Elfin', 'Aquos', NULL),
(9, 'Helios', 'Pyrus', NULL),
(10, 'Viper Helios', 'Pyrus', 'Darkus'),
(11, 'Neo Dragonoid', 'Pyrus', NULL),
(12, 'Wilda', 'Subterra', NULL),
(13, 'Percival', 'Darkus', NULL),
(14, 'Nemus', 'Haos', NULL),
(15, 'Vulcan', 'Subterra', NULL),
(16, 'Cross Dragonoid', 'Pyrus', 'Ventus'),
(17, 'Alpha Hydranoid', 'Darkus', NULL),
(18, 'Blade Tigrerra', 'Haos', NULL),
(19, 'Storm Skyress', 'Ventus', NULL),
(20, 'Cyclone Percival', 'Darkus', NULL),
(21, 'Maxus Dragonoid', 'Pyrus', 'Ventus'),
(22, 'Lumagrowl', 'Haos', NULL),
(23, 'Strikeflier', 'Ventus', 'Pyrus'),
(24, 'Meta Dragonoid', 'Pyrus', NULL),
(25, 'Drago', 'Pyrus', NULL),
(26, 'Helix Drago', 'Pyrus', NULL),
(27, 'Taylean', 'Aquos', NULL),
(28, 'Mutant Elfin', 'Aquos', 'Ventus'),
(29, 'Flash Ingram', 'Ventus', NULL),
(30, 'Dharak', 'Darkus', NULL),
(31, 'Zenthon', 'Darkus', 'Pyrus'),
(32, 'Krakenoid', 'Aquos', NULL),
(33, 'Razenoid', 'Darkus', NULL),
(34, 'Evo Helios', 'Pyrus', 'Darkus'),
(35, 'Aranaut', 'Haos', NULL),
(36, 'Plitheon', 'Subterra', NULL),
(37, 'Coredem', 'Subterra', 'Ventus'),
(38, 'Strikeflier', 'Ventus', 'Pyrus'),
(39, 'Linehalt', 'Darkus', 'Haos'),
(40, 'Hawktor', 'Ventus', NULL),
(41, 'Ventus Drago', 'Ventus', NULL),
(42, 'Gargonoid', 'Darkus', NULL),
(43, 'Aquos Preyas', 'Aquos', NULL),
(44, 'Centipoid', 'Subterra', NULL),
(45, 'Mantris', 'Ventus', 'Darkus'),
(46, 'Serpenoid', 'Pyrus', 'Darkus'),
(47, 'Fusion Dragonoid', 'Pyrus', NULL),
(48, 'JetKor', 'Aquos', 'Pyrus'),
(49, 'Exedra', 'Darkus', 'Haos'),
(50, 'Lythirus', 'Aquos', 'Subterra');